name = "InvariantPointAttention"
uuid = "814a5788-1061-474f-a71f-873f087d5d12"
authors = ["Lukas Billera and Ben Murrell <benjamin.murrel@ki.se>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.9"
