name = "InvariantPointAttention"
uuid = "814a5788-1061-474f-a71f-873f087d5d12"
authors = ["Lukas Billera and Ben Murrell <benjamin.murrell@ki.se>"]
version = "0.1.3"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ChainRulesCore = "1"
Flux = "0.14, 0.15, 0.16"
LinearAlgebra = "1"
julia = "1.9"

[extras]
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Flux", "ChainRulesTestUtils"]
